[package]
name = "server-side"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "../app" }
axum = "0.6.18"
tokio = { version = "1.28.2", features = ["full"] }
